import { EntitySchema } from "teaql-ts/sql/core";

export const ENTITY_SCHEMAS: Record<string, EntitySchema> = {
"CommercePlatform": {
    table: "commerce_platform_data",
    columns: {"id": { columnName: "id", logicalType: "integer", decode: "string" }, "name": { columnName: "name", logicalType: "text", decode: "native" }, "createTime": { columnName: "create_time", logicalType: "date", decode: "date" }, "updateTime": { columnName: "update_time", logicalType: "date", decode: "date" }, "version": { columnName: "version", logicalType: "integer", decode: "number" }},
    relations: {"customerList": { targetEntity: "Customer", localKey: "id", foreignKey: "commercePlatform", many: true }, "orderStatusList": { targetEntity: "OrderStatus", localKey: "id", foreignKey: "commercePlatform", many: true }, "customerOrderList": { targetEntity: "CustomerOrder", localKey: "id", foreignKey: "commercePlatform", many: true }, "productList": { targetEntity: "Product", localKey: "id", foreignKey: "commercePlatform", many: true }, "orderLineList": { targetEntity: "OrderLine", localKey: "id", foreignKey: "commercePlatform", many: true }, "orderSearchPresetList": { targetEntity: "OrderSearchPreset", localKey: "id", foreignKey: "commercePlatform", many: true }}},
"Customer": {
    table: "customer_data",
    columns: {"id": { columnName: "id", logicalType: "integer", decode: "string" }, "name": { columnName: "name", logicalType: "text", decode: "native" }, "email": { columnName: "email", logicalType: "text", decode: "native" }, "commercePlatform": { columnName: "commerce_platform", logicalType: "integer", decode: "string" }, "createTime": { columnName: "create_time", logicalType: "date", decode: "date" }, "updateTime": { columnName: "update_time", logicalType: "date", decode: "date" }, "version": { columnName: "version", logicalType: "integer", decode: "number" }},
    relations: {"customerOrderList": { targetEntity: "CustomerOrder", localKey: "id", foreignKey: "customer", many: true }}},
"OrderStatus": {
    table: "order_status_data",
    columns: {"id": { columnName: "id", logicalType: "integer", decode: "string" }, "name": { columnName: "name", logicalType: "text", decode: "native" }, "code": { columnName: "code", logicalType: "text", decode: "native" }, "color": { columnName: "color", logicalType: "text", decode: "native" }, "displayOrder": { columnName: "display_order", logicalType: "decimal", decode: "number" }, "commercePlatform": { columnName: "commerce_platform", logicalType: "integer", decode: "string" }, "version": { columnName: "version", logicalType: "integer", decode: "number" }},
    relations: {"customerOrderList": { targetEntity: "CustomerOrder", localKey: "id", foreignKey: "status", many: true }}},
"CustomerOrder": {
    table: "customer_order_data",
    columns: {"id": { columnName: "id", logicalType: "integer", decode: "string" }, "orderNumber": { columnName: "order_number", logicalType: "text", decode: "native" }, "orderDate": { columnName: "order_date", logicalType: "date", decode: "date" }, "totalAmount": { columnName: "total_amount", logicalType: "decimal", decode: "number" }, "status": { columnName: "status", logicalType: "integer", decode: "string" }, "customer": { columnName: "customer", logicalType: "integer", decode: "string" }, "commercePlatform": { columnName: "commerce_platform", logicalType: "integer", decode: "string" }, "createTime": { columnName: "create_time", logicalType: "date", decode: "date" }, "updateTime": { columnName: "update_time", logicalType: "date", decode: "date" }, "version": { columnName: "version", logicalType: "integer", decode: "number" }},
    relations: {"orderLineList": { targetEntity: "OrderLine", localKey: "id", foreignKey: "customerOrder", many: true }}},
"Product": {
    table: "product_data",
    columns: {"id": { columnName: "id", logicalType: "integer", decode: "string" }, "name": { columnName: "name", logicalType: "text", decode: "native" }, "sku": { columnName: "sku", logicalType: "text", decode: "native" }, "imageUrl": { columnName: "image_url", logicalType: "text", decode: "native" }, "commercePlatform": { columnName: "commerce_platform", logicalType: "integer", decode: "string" }, "createTime": { columnName: "create_time", logicalType: "date", decode: "date" }, "updateTime": { columnName: "update_time", logicalType: "date", decode: "date" }, "version": { columnName: "version", logicalType: "integer", decode: "number" }},
    relations: {"orderLineList": { targetEntity: "OrderLine", localKey: "id", foreignKey: "product", many: true }}},
"OrderLine": {
    table: "order_line_data",
    columns: {"id": { columnName: "id", logicalType: "integer", decode: "string" }, "customerOrder": { columnName: "customer_order", logicalType: "integer", decode: "string" }, "product": { columnName: "product", logicalType: "integer", decode: "string" }, "productName": { columnName: "product_name", logicalType: "text", decode: "native" }, "sku": { columnName: "sku", logicalType: "text", decode: "native" }, "quantity": { columnName: "quantity", logicalType: "integer", decode: "native" }, "commercePlatform": { columnName: "commerce_platform", logicalType: "integer", decode: "string" }, "createTime": { columnName: "create_time", logicalType: "date", decode: "date" }, "version": { columnName: "version", logicalType: "integer", decode: "number" }}},
"OrderSearchPreset": {
    table: "order_search_preset_data",
    columns: {"id": { columnName: "id", logicalType: "integer", decode: "string" }, "name": { columnName: "name", logicalType: "text", decode: "native" }, "filterJson": { columnName: "filter_json", logicalType: "text", decode: "native" }, "requestId": { columnName: "request_id", logicalType: "text", decode: "native" }, "ownerUserId": { columnName: "owner_user_id", logicalType: "text", decode: "native" }, "commercePlatform": { columnName: "commerce_platform", logicalType: "integer", decode: "string" }, "createTime": { columnName: "create_time", logicalType: "date", decode: "date" }, "updateTime": { columnName: "update_time", logicalType: "date", decode: "date" }, "version": { columnName: "version", logicalType: "integer", decode: "number" }}}
};